language: cpp
sudo: required
dist: trusty

before_install:
  - scripts/cmake.sh
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install g++-5 -y
  - export CXX=g++-5
script: cd build && cmake .. && make && ./unittest

os:
  - linux
compiler:
  - gcc
