language: cpp
sudo: required
dist: trusty

before_install:
  - if [ "$TRAVIS_OS_NAME" == linux ]; then ./tools/travis_dependencies.sh; export CXX=g++-5; fi
script: cd build && cmake .. && make && ./unittest

os:
  - linux
  - osx
compiler:
  - gcc
