language: cpp
sudo: required
dist: trusty
group: deprecated-2017Q4
services:
  -docker

notifications:
  slack: jassv2:IX7Yf0N9YJ0rM4OFVvCTrgCY

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "luglXydd+BtaGAHZwVpkszfoeEIciMrSalJ9BJ63wTZa/3A4iwtX//qSL/gyGIHEPz1RmX6g2T+fF1A+WaPw6dD9VkDo2/KsWOatX7X8h2xh1hWq4MZZvcLSTyKKvqnXZnDBLZkK9nVEaJLJEYI3Ln4NqGsXqp7bCHxty9D8Eotfagnp73PSzBJ5JEK0Gcoq4VpTQLcmqjhfPNtRZadTPeuvrZJXAFARxQn8x78q5sWBswXypFfn6gZVOX1IZu+IhNWibo49CophpyW8ZKml/KIsvJSaJPPiee2/GK5se0Dg4W3t5DIab3+Y2V5PE1LXPdqZeLrkTtZqDF8zTnBHd5hLcQqBPgjfgDp0KfNAE7LP8hk+Tumaw4D6QC40xuZmYaeKJM7mCF9tAjPYwBRi+ffYGleBaF4iiB2kvNnXMqWNJ0pc17p/r30p/svp9hnFpoob/5Hy4r+DCjXsbhnoaVmDB5dpRk6JV6yX6DzZEgKuh6zKPsNop1RZsHQzjr2Ao6XrFFa0nPCVlnTjGtuQtBzdQqPtuLFGSxyee7hQD2uBChKv6jZVOOnPOuG7MIwdAJB9KlZerHU3WXE/JZX2W0jaqfB/UuO0pOL1jrXsm6da668DnMSmpe/DU3RzKjmQduNp7n6/TvH2IGrI/uuCxBG1l8seVeNp39jJ5QOCxbs="

before_install:
  - if [ "$TRAVIS_BRANCH" != "coverity_scan" -a "$TRAVIS_OS_NAME" == "linux" ]; then 
      docker pull andrewtrotman/build-with-gcc;
      docker run andrewtrotman/build-with-gcc -e TRAVIS_JOB_ID="$TRAVIS_JOB_ID" -e TRAVIS_BRANCH="$TRAVIS_BRANCH";
    fi
  - if [ "$TRAVIS_BRANCH" != "coverity_scan" -a "$TRAVIS_OS_NAME" == osx ]; then 
      system_profiler SPHardwareDataType | grep "Model Identifier";
      sysctl -n machdep.cpu.brand_string;
      system_profiler SPSoftwareDataType;
      xcodebuild -version;
      git clone https://github.com/andrewtrotman/JASSv2.git;
      cd JASSv2;
      cd build;
      ../docker/mac_build.sh;
      xcodebuild -version;
    fi
  - if [ "$TRAVIS_BRANCH" == "coverity_scan" -a "$TRAVIS_OS_NAME" == osx ]; then 
      echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
    fi

install: true
script: true
after_success: true

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        # COVERITY TOKEN
        - secure: "Vj49la7ApuC2IVb+2cU563BPVHUbmXlcQ6W91wb8BAGQNOtsmm9KlXTS3mIQ4NxZJgfHxW5Pnx/H6VNBaG21QGK2J7/DB8NMmmmOQwF6vDSULFt8cOXmjLqvblPOnqfvTQbWxNmX3toOZJN1719k5csdNKHKsZTEj6nQT13fsGar+lcQhf+wsKmmEOMzN0Wo0jiqj4naLqaxs0NhUKldsfI8LrswxxW0CUBmvBeVB3ZnxPyKoPMkLASYosxNI0tsr0teuny5s53DwgUW5kBjMZPNLWitkiyJFeFKjQOEhyJ07zEbm4e0bhWd5QUKFIsRI8paY8vo3OQzP1s04A64zv1fP2PqbvDLmm/5z0jVUql4AzcSmXOCeK4mzaGMFC6a4FLPeSJDTj0HkkoJIo3dpOGJ4BQFueSKatsBB2bc9uEugFl2hV6/nrHHEmVkjFbZzFpWnZC7ovX8jGasqC2+iffWB8Lp3hAAqDMIeqUVLnHinJzv8VGJd9gJivqX1iIO6rY5Vys3pb0TJfjKc8xF5NvxPPko7HP9U1fvqcegnTbuhYqlVNxnRNLt2qGracNRXDu1SE3RFk8rFxJ+GP/rGX4b1WXjtr9f6ob7+jp7QAh0hijcjVSxu8FdB2P3r6AKEy83D5JyHqRglI5g3NWSHDvxJ/p3XlUV5mYLGoly5CE="

    - os: osx
      compiler: clang

branches:
  only:
    - master
    - coverity_scan

addons:
  coverity_scan:
    project:
      name: "andrewtrotman/JASSv2"
      description: "JASSv2 Coverity Scan Branch"
    notification_email: andrew@trotman.com
    build_command_prepend: "cd build && cmake -D FORCE_CMAKE_BUILD_TYPE=Debug .."
    build_command: "make"
    branch_pattern: coverity_scan
