[package]
name = "ioqp_compress"
version = "0.1.0"
edition = "2021"

[lib]
name = "ioqp_lib"
path = "source/compress_integer_ioqp.rs"
crate-type = ["staticlib"]

[dependencies]
bitpacking = "0.9.2"
byteorder = "1.5.0"
streamvbyte = "0.1.1"
